# Use a imagem base do Node.js
FROM node:18

# Crie um diretório de trabalho
WORKDIR /usr/src/app

# Copie os arquivos do package.json e package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie todo o restante do código para dentro do container
COPY . .

# Exponha a porta que sua API irá rodar
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["node", "server.mjs"]
